modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "All Rights Reserved"

[[mods]]
modId = "cobblemonarmours"
version = "${version}"
displayName = "Cobblemon: Armours"
authors = "DAN2026"
description = '''
Cobblemon Side-mod that introduces 10 evolution armour sets with set bonuses.
'''
#logoFile = ""

[[mixins]]
config = "cobblemonarmours.mixins.json"

[[dependencies.cobblemonarmours]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonarmours]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonarmours]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemonarmours]]
modId = "architectury"
mandatory = true
versionRange = "[13,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.cobblemonarmours]]
modId = "jei"
type = "optional"
versionRange = "[19.0,)"